#!/bin/bash
clear
target=$1
mkdir -p build
cd build
cmake .. -G "MinGW Makefiles"
mingw32-make.exe all
./$target



# CMakee version 3.10
# mkdir -p build
# cd build
# cmake ..
# make all
# ./$target


# CMake version 3.15+
# clear
# target=$1
# cmake -S . -B build
# cmake --build build --config Debug --target $target
# ./build/$target
